In [1]:
import torch

## 2.1 Создание нейронов и полносвязных слоев

2.1.1. Используя операции над матрицами и векторами из библиотеки `torch`, реализовать нейрон с заданными весами `weights` и `bias`. Прогнать вектор `inputs` через нейрон и вывести результат. 

In [2]:
class Neuron:
  def __init__(self, weights, bias):
    self.weights = weights
    self.bias = bias
    # <создать атрибуты объекта weights и bias>
  
  def forward(self, inputs):
    return torch.dot(self.weights, inputs) + self.bias
    # <реализовать логику нейрона>

In [6]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([-0.2, 0.3, -0.5, 0.7])
bias = 3.14

Ner = Neuron(weights, bias)
Ner.forward(inputs)

tensor(4.8400)

2.1.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой с заданными весами `weights` и `biases`. Прогнать вектор `inputs` через слой и вывести результат. 

In [7]:
class Linear:
  def __init__(self, weights, biases):
    self.weights = weights
    self.biases = biases
    # <создать атрибуты объекта weights и biases>
  
  def forward(self, inputs):
    return torch.mv(self.weights, inputs) + self.biases
    # <реализовать логику слоя>

In [8]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([[-0.2, 0.3, -0.5, 0.7],
                        [0.5, -0.91, 0.26, -0.5],
                        [-0.26, -0.27, 0.17, 0.87]])

biases = torch.tensor([3.14, 2.71, 7.2])

Line = Linear(weights, biases)
Line.forward(inputs)

tensor([ 4.8400,  0.1700, 10.3900])

2.1.3 Реализовать полносвязный слой из __2.1.2__ таким образом, чтобы он мог принимать на вход матрицу (батч) с данными. Продемонстрировать работу.
Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.


In [11]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])
weights = torch.tensor([[-0.2, 0.3, -0.5, 0.7],
                        [0.5, -0.91, 0.26, -0.5],
                        [-0.26, -0.27, 0.17, 0.87]]).T

class LinearBatch:
  def __init__(self, weights, biases):
    self.weights = weights
    self.biases = biases

  def forward(self, inputs):
    return torch.mm(inputs, self.weights) + self.biases

LB = LinearBatch(weights, biases)
LB.forward(inputs)

tensor([[ 3.7900,  0.9200,  9.0850],
        [ 6.1400, -2.1000,  6.9000],
        [ 2.0400,  0.7610,  6.7260]])

2.1.4 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой из `n_neurons` нейронов с `n_features` весами у каждого нейрона (инициализируются из стандартного нормального распределения). Прогнать вектор `inputs` через слой и вывести результат. Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.

In [23]:
from torch.nn import Linear as TorchLinear

In [24]:
m = TorchLinear(20, 30)
X = torch.randn(140, 20)
Y = m(X)
Y.size()

torch.Size([140, 30])

In [25]:
Y

tensor([[ 0.2128,  0.3364,  0.0752,  ...,  0.2351,  1.0376, -0.8680],
        [-0.1714, -0.9429,  0.1837,  ..., -0.0611,  1.2930,  0.3778],
        [ 0.3384, -0.3082,  0.5410,  ...,  0.4397, -0.2206,  0.2846],
        ...,
        [-0.4076, -1.3893, -0.2202,  ...,  0.6897, -0.0628, -0.7847],
        [-0.7865,  0.6475,  0.2328,  ...,  0.8502, -0.4547, -0.1917],
        [ 0.1910, -0.1818, -0.7219,  ..., -0.3727, -0.9511, -0.8065]],
       grad_fn=<AddmmBackward0>)

In [26]:
class LinearNN(TorchLinear):
  def __init__(self, n_features, n_neurons):
    super().__init__(in_features=n_features, out_features=n_neurons)
    self.weights = torch.randn(n_features, n_neurons)
    self.biases = torch.randn(n_neurons)
    # <создать атрибуты объекта weights и biases>
  
  def forward(self, inputs):
    return torch.matmul(inputs, self.weights) + self.biases
    # <реализовать логику слоя>

In [27]:
m1 = LinearNN(n_features=4, n_neurons=3)
inputs = torch.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])
m1.forward(inputs)

tensor([[ -6.4885, -11.6820,   1.9130],
        [ -2.7882,  -9.0996,  -3.6584],
        [ -3.2235,  -3.3459,   1.6263]])

In [28]:
Y1 = m1(inputs)
Y1

tensor([[ -6.4885, -11.6820,   1.9130],
        [ -2.7882,  -9.0996,  -3.6584],
        [ -3.2235,  -3.3459,   1.6263]])

2.1.5 Используя решение из __2.1.4__, создать 2 полносвязных слоя и пропустить матрицу `inputs` последовательно через эти два слоя. Количество нейронов в первом слое выбрать произвольно, количество нейронов во втором слое выбрать так, чтобы результатом прогона являлась матрица (3x7). 

In [30]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

L1 = LinearNN(n_features=4, n_neurons=10)
L2 = LinearNN(n_features=10, n_neurons=7)

result = L2(L1(inputs))
result

tensor([[ -5.2885,  -3.2191,  -0.3780,  -4.9325, -11.0479,  -8.2356,  10.9490],
        [ 17.0942,   6.2597, -11.8401,   0.4136,  18.3528,  14.3164,   3.0448],
        [  2.7318,   8.4768,   6.4851,  -9.4748,  -3.0124,  -3.2237,  10.9897]])

In [31]:
result.shape

torch.Size([3, 7])

## 2.2 Создание функций активации

2.2.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ReLU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/f4353f4e3e484130504049599d2e7b040793e1eb)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [32]:
class ReLU:
  def forward(self, inputs):
    inputs[inputs < 0] = 0
    return inputs

inputs = torch.randn(4, 3)
relu = ReLU()

inputs

tensor([[ 0.7622, -0.3136,  1.9263],
        [ 0.3659,  0.1228,  0.2715],
        [ 0.8438, -1.2858, -0.2400],
        [-1.4759,  0.3299, -2.6246]])

In [33]:
relu.forward(inputs)

tensor([[0.7622, 0.0000, 1.9263],
        [0.3659, 0.1228, 0.2715],
        [0.8438, 0.0000, 0.0000],
        [0.0000, 0.3299, 0.0000]])

2.2.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации softmax:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/6d7500d980c313da83e4117da701bf7c8f1982f5)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации. Строки матрицы трактовать как выходы линейного слоя некоторого классификатора для 4 различных примеров.

In [36]:
class Softmax:
  def forward(self, inputs):
    high = torch.exp(inputs)
    down = torch.sum(torch.exp(inputs), dim=1).view(-1, 1)
    return high / down

inputs = torch.randn(4, 3)
softm = Softmax()

inputs

tensor([[ 0.7072,  0.1823, -0.7617],
        [ 0.0643,  0.6154, -1.0999],
        [ 0.4359, -0.3603, -0.0665],
        [ 0.4766,  0.4565, -1.5229]])

In [37]:
softm.forward(inputs)

tensor([[0.5489, 0.3247, 0.1263],
        [0.3282, 0.5694, 0.1024],
        [0.4864, 0.2194, 0.2943],
        [0.4727, 0.4633, 0.0640]])

2.2.3 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ELU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/eb23becd37c3602c4838e53f532163279192e4fd)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [45]:
class ELU:
  def __init__(self, alpha):
    self.alpha = alpha

  def forward(self, inputs):
    inputs[inputs < 0] = (torch.exp(inputs[inputs < 0]) - 1) * self.alpha
    return inputs

inputs = torch.randn(4, 3)
elu = ELU(alpha=1)

inputs

tensor([[-0.2451, -0.0139,  1.9679],
        [ 1.4214,  0.1181,  0.7175],
        [-1.2775, -0.6713,  0.1963],
        [-1.1186, -1.0180, -1.8553]])

In [46]:
elu.forward(inputs)

tensor([[-0.2174, -0.0138,  1.9679],
        [ 1.4214,  0.1181,  0.7175],
        [-0.7213, -0.4890,  0.1963],
        [-0.6733, -0.6387, -0.8436]])

## 2.3 Создание функции потерь

2.3.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь MSE:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/e258221518869aa1c6561bb75b99476c4734108e)

Создать полносвязный слой с 1 нейроном, прогнать через него батч `inputs` и посчитать значение MSE, трактуя вектор `y` как вектор правильных ответов.

In [54]:
class MSELoss:
  def forward(self, y_pred, y_true):
    return ((y_true - y_pred) ** 2).mean()

In [55]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

y = torch.tensor([2, 3, 4])
y

tensor([2, 3, 4])

In [56]:
L = LinearNN(n_features=4, n_neurons=1)
mse = MSELoss()

Y_pred = L(inputs)
Y_pred

tensor([[-4.6159],
        [-1.1633],
        [-4.4178]])

In [57]:
print(f"MSE: {mse.forward(Y_pred, y)}")

MSE: 44.119606018066406


2.3.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь Categorical Cross-Entropy:

<img src="https://i.ibb.co/93gy1dN/Screenshot-9.png" width="200">

Создать полносвязный слой с 3 нейронами и прогнать через него батч `inputs`. Полученный результат пропустить через функцию активации softmax. Посчитать значение CCE, трактуя вектор `y` как вектор правильных ответов.

In [61]:
class CategoricalCrossentropyLoss:
  def forward(self, y_pred, y_true):
    return -1 * (y_true * torch.log(y_pred)).sum(1)

In [69]:
inputs = torch.tensor([[1, 2, 3, 2.5],
                        [2, 5, -1, 2], 
                        [-1.5, 2.7, 3.3, -0.8]])
y = torch.tensor([1, 0, 0])
y

tensor([1, 0, 0])

In [72]:
L = LinearNN(n_features=4, n_neurons=3)
softmax = Softmax()
cce = CategoricalCrossentropyLoss()

L(inputs)

tensor([[ 6.8174,  4.7629,  2.7025],
        [ 2.8747, 13.3686,  4.1879],
        [-1.9674, -2.5868, -1.7733]])

In [73]:
softmax.forward(L(inputs))

tensor([[8.7376e-01, 1.1197e-01, 1.4266e-02],
        [2.7702e-05, 9.9987e-01, 1.0300e-04],
        [3.6331e-01, 1.9556e-01, 4.4112e-01]])

In [74]:
print(f"CCE: {cce.forward(softmax.forward(L(inputs)), y)}")

CCE: tensor([ 0.1349, 10.4940,  1.0125])


2.3.3 Модифицировать 2.3.1, добавив L2-регуляризацию.

<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/d92ca2429275bfdc0474523babbafe014ca8b580)"/>


In [77]:
class MSELossL2:
  def __init__(self, lambda_, layer, W=0.1):
    # <создать атрибут объекта alpha>
    self.lambda_ = lambda_
    self.layer = layer
    self.layer.W = W

  def data_loss(self, y_pred, y_true):
    # <подсчет первого слагаемого из формулы>
    return (y_true - y_pred) ** 2

  def reg_loss(self, layer):
    # используйте атрибуты объекта layer, в которых хранятся веса слоя
    return self.lambda_ * (layer.W ** 2)

  def forward(self, y_pred, y_true):
    return self.data_loss(y_pred, y_true) + self.reg_loss(self.layer)

In [78]:
inputs = torch.tensor([[1, 2, 3, 2.5],
                        [2, 5, -1, 2],
                        [-1.5, 2.7, 3.3, -0.8]])
y = torch.tensor([1, 0, 0])
y

tensor([1, 0, 0])

In [85]:
L = LinearNN(n_features=4, n_neurons=3)
L_out = L(inputs)

softmax = Softmax()
mse2 = MSELossL2(1.5, L_out)

L_out

tensor([[ 0.8129, -2.2347, -1.3714],
        [ 2.6880,  1.3600,  1.4253],
        [ 1.6975,  6.1108,  3.8597]])

In [86]:
softmax.forward(L_out)

tensor([[0.8620, 0.0409, 0.0970],
        [0.6460, 0.1712, 0.1828],
        [0.0108, 0.8949, 0.0942]])

In [87]:
print(f"MSE 2: {mse2.forward(softmax.forward(L_out), y)}")

MSE 2: tensor([[0.0340, 0.0167, 0.0244],
        [0.1403, 0.0443, 0.0484],
        [0.9934, 0.8159, 0.0239]])


## 2.4 Обратное распространение ошибки

2.4.1 Используя один нейрон и SGD (1 пример за шаг), решите задачу регрессии

In [ ]:
from sklearn.datasets import make_regression

X, y, coef = make_regression(n_features=4, n_informative=4, coef=True, bias=0.5)
X = # <преобразуйте массивы numpy в тензоры torch с типом torch.float32
y = # <преобразуйте массивы numpy в тензоры torch с типом torch.float32

[Граф вычислений для этой задачи](https://i.ibb.co/2dhDxZx/photo-2021-02-15-17-18-04.jpg)

2.4.1.1 Реализуйте класс `SquaredLoss`


In [ ]:
class SquaredLoss:
  def forward(self, y_pred, y_true):
    return # <реализовать логику MSE>

  def backward(self, y_pred, y_true):
    self.dinput = # df/dc


2.4.1.2. Модифицируйте класс `Neuron` из __2.1.1__:

  1) Сделайте так, чтобы веса нейрона инициализировались из стандартного нормального распределения

  2) Реализуйте расчет градиента относительно весов `weights` и `bias`

In [ ]:
class Neuron:
  def __init__(self, n_inputs):
    # <создать атрибуты объекта weights и bias>
    pass
  
  def forward(self, inputs):
    return # <реализовать логику нейрона>
  
  def backward(self, dvalue):
    # dvalue - значение производной, которое приходит нейрону от следующего слоя сети
    # в данном случае это будет значение df/dc (созданное методом backwards у объекта MSELoss)
    self.dweights = # df/dW
    self.dinput =  # df/wX
    self.dbias = # df/db


2.4.1.3 Допишите цикл для настройки весов нейрона

[SGD](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%BE%D1%85%D0%B0%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D0%B3%D1%80%D0%B0%D0%B4%D0%B8%D0%B5%D0%BD%D1%82%D0%BD%D1%8B%D0%B9_%D1%81%D0%BF%D1%83%D1%81%D0%BA)

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/dda3670f8a8996a0d3bf80856bb4a166cc8db6d4)

In [ ]:
n_inputs = # <размерность элемента выборки >
learning_rate = 0.1 #  скорость обучения
n_epoch = 100 #  количество эпох

neuron = Neuron(n_inputs)
loss = MSELoss()

losses = []
for epoch in range(100):
  for x_example, y_example in zip(X, y):
    # forward pass
    y_pred = # <прогон через нейрон>
    curr_loss = # <прогон через функцию потерь>
    losses.append(curr_loss)

    # backprop
    # <вызов методов backward>
    # обратите внимание на последовательность вызовов: от конца к началу

    # <шаг оптимизации для весов (weights и bias) нейрона>

2.4.2 Решите задачу 2.4.1, используя пакетный градиентный спуск

Вычисления для этой задачи: 
[1](https://i.ibb.co/rmtQT6P/photo-2021-02-15-18-00-43.jpg)
[2](https://i.ibb.co/NmCFVnQ/photo-2021-02-15-18-01-17.jpg)

2.4.1.1 Модифицируйте класс `MSELoss` из __2.3.1__, реализовав расчет производной относительно предыдущего слоя с учетом того, что теперь работа ведется с батчами, а не с индивидуальными примерами
 

In [ ]:
class MSELoss:
  def forward(self, y_pred, y_true):
    return # <реализовать логику MSE>

  def backward(self, y_pred, y_true):
    self.dinput = # df/dy^


2.4.2.2. Модифицируйте класс `Neuron` из __2.4.1.2__:

  1) Реализуйте метод `forward` таким образом, чтобы он мог принимать на вход матрицу (батч) с данными. 

  2) Реализуйте расчет градиента относительно весов `weights` и `bias` с учетом того, что теперь работа ведется с батчами, а не с индивидуальными примерами

In [ ]:
class Neuron:
  def __init__(self, n_inputs):
    # <создать атрибуты объекта weights и bias>
    pass
  
  def forward(self, inputs):
    return # <реализовать логику нейрона>
  
  def backward(self, dvalue):
    # dvalue - значение градиента, которое приходит нейрону от следующего слоя сети
    # в данном случае это будет градиент L по y^ (созданный методом backwards у объекта MSELoss)
    self.dweights = # df/dW
    self.dbias = # df/db


2.4.2.3 Допишите цикл для настройки весов нейрона

In [ ]:
n_inputs = # <размерность элемента выборки >
learning_rate = 0.1 #  скорость обучения
n_epoch = 100 #  количество эпох

neuron = Neuron(n_inputs)
loss = MSELoss()


for epoch in range(100):
    # forward pass
    y_pred = # <прогон через нейрон>
    curr_loss = # <прогон через функцию потерь>
    losses.append(curr_loss)

    # backprop
    # <вызов методов backward>
    # обратите внимание на последовательность вызовов: от конца к началу

    # <шаг оптимизации для весов (weights и bias) нейрона>

2.4.3  Используя один полносвязный слой и  пакетный градиетный спуск, решите задачу регрессии из __2.4.1__

2.4.3.1 Модифицируйте класс `Linear` из __2.1.4__. ([вычисление градиентов](https://i.ibb.co/kgVR6m6/photo-2021-02-15-21-30-28.jpg))

In [ ]:
class Linear:
  def __init__(self, n_features, n_neurons):
    # <создать атрибуты объекта weights и biases>
    pass
  
  def forward(self, inputs):
    return # <реализовать логику слоя>

  def backward(self, dvalues):
    self.dweights = # df/dW
    self.dbiases = # df/db
    self.dinputs = # df/dX

2.4.3.2 Создайте слой с одним нейроном. Используя класс MSELoss из 2.4.2, убедитесь, что модель обучается

2.4.4 Используя наработки из 2.4, создайте нейросеть и решите задачу регрессии.

Предлагаемая архитектура: 
1. Полносвязный слой с 10 нейронами
2. Активация ReLU
3. Полносвязный слой с 1 нейроном

In [ ]:
X = torch.linspace(-1, 1, 100).view(-1, 1)
y = X.pow(2) + 0.2 * torch.rand(X.size()) 

In [ ]:
class Activation_ReLU:
  def forward(self, inputs):
    self.inputs = inputs
    self.output = inputs.clip(min=0)
    return self.output
  
  def backward(self, dvalues):
    self.dinputs = dvalues.clone()
    self.dinputs[self.inputs <= 0] = 0

In [ ]:
# создание компонентов сети
# fc1 = 
# relu1 = 
# fc2 = 

loss = MSELoss()
lr = 0.02

ys = []
for epoch in range(2001):
  # <forward pass>
  # fc1 > relu1 > fc2 > loss

  data_loss = # <прогон через функцию потерь>

  if epoch % 200 == 0:
    print(f'epoch {epoch} mean loss {data_loss}')
    ys.append(out)
  
  # <backprop> 
  # loss > fc2 > relu1 > fc1

  # <шаг оптимизации для fc1>

  # <шаг оптимизации для fc2>


In [ ]:
import matplotlib.pyplot as plt

fig, axs = plt.subplots(len(ys), 1, figsize=(10, 40))
for ax, y_ in zip(axs, ys):
  ax.scatter(X.numpy(), y.numpy(), color = "orange")
  ax.plot(X.numpy(), y_.numpy(), 'g-', lw=3)
  ax.set_xlim(-1.05, 1.5)
  ax.set_ylim(-0.25, 1.25)